import React from 'react';
import { Flame, PlusCircle, Settings, ShieldCheck, Sparkles, Terminal, Youtube } from 'lucide-react';
import { AIConfig, SystemStatus } from '../types';
interface Props { systemStatus: SystemStatus | null; aiConfig: AIConfig; approvalMode: boolean; onToggleApprovalMode?: () => void; onOpenSettings: () => void; onOpenGenerator: () => void; activeTab: 'pipeline' | 'approvals' | 'analytics'; setActiveTab: (tab: 'pipeline' | 'approvals' | 'analytics') => void; pendingCount: number; }
export const Navbar: React.FC<Props> = ({ systemStatus, aiConfig, onOpenSettings, onOpenGenerator, activeTab, setActiveTab, pendingCount }) => {
  const provider: Record<AIConfig['provider'], string> = { gemini: 'Gemini', claude: 'Claude', openai: 'OpenAI', openrouter: 'OpenRouter', ollama: 'Ollama', kimi: 'Kimi', glm: 'GLM' };
  const tabs = [{ key: 'approvals' as const, label: 'Aprovações', icon: ShieldCheck }, { key: 'pipeline' as const, label: 'Pipeline', icon: Flame }, { key: 'analytics' as const, label: 'Canal e dados', icon: Youtube }];
  return <header className="sticky top-0 z-40 border-b border-neutral-800 bg-neutral-950/90 backdrop-blur-md"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex min-h-16 items-center justify-between gap-3 py-2"><div className="flex items-center gap-3"><Youtube className="h-8 w-8 text-red-500" /><div><div className="flex items-center gap-2"><strong className="text-lg text-white">AutoTube</strong><a href="https://www.youtube.com/@loopsonorobr" target="_blank" rel="noopener noreferrer" className="rounded border border-red-900/50 bg-red-950/60 px-2 py-0.5 font-mono text-xs text-red-300">@loopsonorobr</a></div><p className="hidden text-xs text-neutral-400 sm:block">Assistente editorial com revisão humana</p></div></div><nav aria-label="Navegação" className="hidden items-center gap-1 rounded-xl border border-neutral-800 bg-neutral-900 p-1 md:flex">{tabs.map(({key,label,icon:Icon}) => <button key={key} onClick={() => setActiveTab(key)} className={`flex items-center gap-2 rounded-lg px-3 py-1.5 text-sm ${activeTab === key ? 'bg-neutral-800 text-white' : 'text-neutral-400'}`}><Icon className="h-4 w-4" />{label}{key === 'approvals' && pendingCount > 0 && <span className="rounded-full bg-amber-500 px-1.5 text-xs text-black">{pendingCount}</span>}</button>)}</nav><div className="flex items-center gap-2"><span role="status" title="A aprovação humana não pode ser desligada." className="flex items-center gap-1 rounded-xl border border-emerald-500/40 bg-emerald-950/40 px-2 py-2 text-xs text-emerald-300"><ShieldCheck className="h-4 w-4" /><span className="hidden sm:inline">Aprovação ligada</span></span><button onClick={onOpenGenerator} className="flex items-center gap-1 rounded-xl bg-red-600 px-3 py-2 text-sm text-white"><PlusCircle className="h-4 w-4" /><span className="hidden sm:inline">Rascunho</span></button><button onClick={onOpenSettings} title="Configurações" className="rounded-xl border border-neutral-800 bg-neutral-900 p-2 text-neutral-300"><Settings className="h-4 w-4" /></button></div></div><div className="flex flex-wrap items-center justify-between gap-2 border-t border-neutral-900 py-1.5 text-xs text-neutral-400"><div className="flex items-center gap-2"><Terminal className="h-3.5 w-3.5" />Node.js: {systemStatus?.nodeVersion || 'dado não disponível'}</div><div className="flex items-center gap-2"><Sparkles className="h-3.5 w-3.5 text-sky-400" />{provider[aiConfig.provider]} · {aiConfig.model}</div><div>Upload/Analytics privado: não conectados</div></div></div></header>;
};
